/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.AerolineaImp;
import dao.DiaImp;
import dao.DiaProgramaImp;
import dao.ProgramaVueloImp;
import interfacesDao.DAOAerolinea;
import interfacesDao.DAODia;
import interfacesDao.DAODiaPrograma;
import interfacesDao.DAOProgramaVuelo;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Aerolinea;
import logica.Dia;
import logica.DiaPrograma;
import logica.ProgramaVuelo;
import reportepdf.Plantilla;

/**
 *
 * @author migue
 */
public class VistaProgramaVuelo extends javax.swing.JFrame {

    CargarComboBox metodosCargarVista = new CargarComboBox();

    public VistaProgramaVuelo() {
        initComponents();

        //Cargamos ComboBox
        metodosCargarVista.comboBoxAerolinea(lineaAComboBox);
        metodosCargarVista.comboBoxAeropuertoPlan(cbAeroPlan);
        metodosCargarVista.comboBoxAeropuertoPlan(cbAeroOrigen);
        metodosCargarVista.comboBoxAeropuertoPlan(cbAeroDestino);

        //Cargando Dias
        DAODia daoDia = new DiaImp();
        List<Dia> listaDias;
        try {
            listaDias = daoDia.listar();
            cbxDia1.setText(listaDias.get(0).getAnomdia());
            cbxDia2.setText(listaDias.get(1).getAnomdia());
            cbxDia3.setText(listaDias.get(2).getAnomdia());
            cbxDia4.setText(listaDias.get(3).getAnomdia());
            cbxDia5.setText(listaDias.get(4).getAnomdia());
            cbxDia6.setText(listaDias.get(5).getAnomdia());
            cbxDia7.setText(listaDias.get(6).getAnomdia());
        } catch (Exception ex) {
            Logger.getLogger(VistaProgramaVuelo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lineaAComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbAeroPlan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbAeroOrigen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbAeroDestino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbxDia1 = new javax.swing.JCheckBox();
        cbxDia2 = new javax.swing.JCheckBox();
        cbxDia3 = new javax.swing.JCheckBox();
        cbxDia4 = new javax.swing.JCheckBox();
        cbxDia5 = new javax.swing.JCheckBox();
        cbxDia6 = new javax.swing.JCheckBox();
        cbxDia7 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Linea Aerea");

        jLabel3.setText("Aeropuerto Plan");

        jLabel4.setText("Aeropuerto Origen");

        jLabel5.setText("Aeropuerto Destino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbAeroPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbAeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbAeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lineaAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineaAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAeroPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Programación Vuelo");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte del dia");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnReporte)
                        .addGap(66, 66, 66)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnEnviar)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btnReporte))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        cbxDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDia2ActionPerformed(evt);
            }
        });

        cbxDia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDia4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDia1)
                    .addComponent(cbxDia2)
                    .addComponent(cbxDia3)
                    .addComponent(cbxDia4)
                    .addComponent(cbxDia5)
                    .addComponent(cbxDia6)
                    .addComponent(cbxDia7))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxDia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia7)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new VistaPasajeros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        //Agregar en bd programa vuelo
        DAOProgramaVuelo daoPrVuelo = new ProgramaVueloImp();
        ProgramaVuelo pr = new ProgramaVuelo();
        String idAeropuerto, idAerOrigen, idAerDestino, codLinea;
        int idPrograma = 0;
        
        idAeropuerto = metodosCargarVista.obtenerIdAeropuerto((String) cbAeroPlan.getSelectedItem());
        idAerOrigen = metodosCargarVista.obtenerIdAeropuerto((String) cbAeroOrigen.getSelectedItem());
        idAerDestino = metodosCargarVista.obtenerIdAeropuerto((String) cbAeroDestino.getSelectedItem());
        codLinea = metodosCargarVista.obtenerIdAerolinea((String) lineaAComboBox.getSelectedItem());
        idPrograma = metodosCargarVista.obtenerIdProgramaVuelo();
        
        pr.setId(idPrograma);
        pr.setCodLinea(codLinea);
        pr.setIdAeropuerto(idAeropuerto);
        pr.setIdDestino(idAerDestino);
        pr.setIdOrigen(idAerOrigen);

        try {
            daoPrVuelo.registrar(pr);
            this.agregarDiasPrograma(idPrograma);
            JOptionPane.showMessageDialog(null, "Programa Vuelo Agregado");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        

    }//GEN-LAST:event_btnEnviarActionPerformed

    public void agregarDiasPrograma(int idPrograma){
        //Agregar en bd diaprograma
        
        DiaPrograma dp = new DiaPrograma();
        String idDia;
        
        if (cbxDia1.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia1.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia2.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia2.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia3.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia3.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia4.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia4.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia5.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia5.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia6.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia6.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia7.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia7.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
    }
    
    public void registrarDiaPrograma(DiaPrograma dp){
        try {
            DAODiaPrograma daoDiaP = new DiaProgramaImp();
            daoDiaP.registrar(dp);
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    private void cbxDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDia2ActionPerformed

    private void cbxDia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDia4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDia4ActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        DAOProgramaVuelo daoPV = new ProgramaVueloImp();
        Plantilla newReport;
        
        try {
            newReport = new Plantilla(daoPV.listarProgramasDia(metodosCargarVista.diaActual()), metodosCargarVista.fechaActual());
            newReport.crearPlantilla();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProgramaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProgramaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProgramaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProgramaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProgramaVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnReporte;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbAeroDestino;
    private javax.swing.JComboBox<String> cbAeroOrigen;
    private javax.swing.JComboBox<String> cbAeroPlan;
    private javax.swing.JCheckBox cbxDia1;
    private javax.swing.JCheckBox cbxDia2;
    private javax.swing.JCheckBox cbxDia3;
    private javax.swing.JCheckBox cbxDia4;
    private javax.swing.JCheckBox cbxDia5;
    private javax.swing.JCheckBox cbxDia6;
    private javax.swing.JCheckBox cbxDia7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> lineaAComboBox;
    // End of variables declaration//GEN-END:variables
}
