/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.AerolineaImp;
import dao.DiaImp;
import dao.DiaProgramaImp;
import dao.ProgramaVueloImp;
import interfacesDao.DAOAerolinea;
import interfacesDao.DAODia;
import interfacesDao.DAODiaPrograma;
import interfacesDao.DAOProgramaVuelo;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Aerolinea;
import logica.Dia;
import logica.DiaPrograma;
import logica.ProgramaVuelo;
import reportepdf.Plantilla;

/**
 *
 * @author migue
 */
public class VistaProgramaVuelo extends javax.swing.JFrame {

    CargarComboBox metodosCargarVista = new CargarComboBox();

    public VistaProgramaVuelo() {
        initComponents();

        //Cargamos ComboBox
        metodosCargarVista.comboBoxAerolinea(lineaAComboBox);
        metodosCargarVista.comboBoxAeropuertoPlan(cbAeroPlan);
        metodosCargarVista.comboBoxAeropuertoPlan(cbAeroOrigen);
        metodosCargarVista.comboBoxAeropuertoPlan(cbAeroDestino);

        //Cargando Dias
        DAODia daoDia = new DiaImp();
        List<Dia> listaDias;
        try {
            listaDias = daoDia.listar();
            cbxDia1.setText(listaDias.get(0).getAnomdia());
            cbxDia2.setText(listaDias.get(1).getAnomdia());
            cbxDia3.setText(listaDias.get(2).getAnomdia());
            cbxDia4.setText(listaDias.get(3).getAnomdia());
            cbxDia5.setText(listaDias.get(4).getAnomdia());
            cbxDia6.setText(listaDias.get(5).getAnomdia());
            cbxDia7.setText(listaDias.get(6).getAnomdia());
        } catch (Exception ex) {
            Logger.getLogger(VistaProgramaVuelo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lineaAComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbAeroPlan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbAeroOrigen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbAeroDestino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        btnReporte = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbxDia1 = new javax.swing.JCheckBox();
        cbxDia2 = new javax.swing.JCheckBox();
        cbxDia3 = new javax.swing.JCheckBox();
        cbxDia4 = new javax.swing.JCheckBox();
        cbxDia5 = new javax.swing.JCheckBox();
        cbxDia6 = new javax.swing.JCheckBox();
        cbxDia7 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programacion de Vuelos");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel1.setText("Linea Aerea");

        cbAeroPlan.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel3.setText("Aeropuerto Plan");

        cbAeroOrigen.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel4.setText("Aeropuerto Origen");

        cbAeroDestino.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel5.setText("Aeropuerto Destino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lineaAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbAeroPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cbAeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel1))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineaAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbAeroOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbAeroPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbAeroDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnReporte.setBackground(new java.awt.Color(0, 0, 0));
        btnReporte.setForeground(new java.awt.Color(255, 255, 204));
        btnReporte.setText("Reporte del dia");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnEnviar.setBackground(new java.awt.Color(0, 0, 0));
        btnEnviar.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 153));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReporte)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbxDia1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbxDia1.setForeground(new java.awt.Color(204, 204, 204));

        cbxDia2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbxDia2.setForeground(new java.awt.Color(204, 204, 204));
        cbxDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDia2ActionPerformed(evt);
            }
        });

        cbxDia3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbxDia3.setForeground(new java.awt.Color(204, 204, 204));

        cbxDia4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbxDia4.setForeground(new java.awt.Color(204, 204, 204));
        cbxDia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDia4ActionPerformed(evt);
            }
        });

        cbxDia5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbxDia5.setForeground(new java.awt.Color(204, 204, 204));

        cbxDia6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbxDia6.setForeground(new java.awt.Color(204, 204, 204));

        cbxDia7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cbxDia7.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDia1)
                    .addComponent(cbxDia2)
                    .addComponent(cbxDia3)
                    .addComponent(cbxDia4)
                    .addComponent(cbxDia5)
                    .addComponent(cbxDia6)
                    .addComponent(cbxDia7))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxDia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDia7)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setText("Programa");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Programación Vuelo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(305, 305, 305))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setText("Dias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(714, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(132, 132, 132)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(jLabel7)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        //Agregar en bd programa vuelo
        DAOProgramaVuelo daoPrVuelo = new ProgramaVueloImp();
        ProgramaVuelo pr = new ProgramaVuelo();
        String idAeropuerto, idAerOrigen, idAerDestino, codLinea;
        int idPrograma = 0;
        
        idAeropuerto = metodosCargarVista.obtenerIdAeropuerto((String) cbAeroPlan.getSelectedItem());
        idAerOrigen = metodosCargarVista.obtenerIdAeropuerto((String) cbAeroOrigen.getSelectedItem());
        idAerDestino = metodosCargarVista.obtenerIdAeropuerto((String) cbAeroDestino.getSelectedItem());
        codLinea = metodosCargarVista.obtenerIdAerolinea((String) lineaAComboBox.getSelectedItem());
        idPrograma = metodosCargarVista.obtenerIdProgramaVuelo();
        
        pr.setId(idPrograma);
        pr.setCodLinea(codLinea);
        pr.setIdAeropuerto(idAeropuerto);
        pr.setIdDestino(idAerDestino);
        pr.setIdOrigen(idAerOrigen);

        try {
            daoPrVuelo.registrar(pr);
            this.agregarDiasPrograma(idPrograma);
            JOptionPane.showMessageDialog(null, "Programa Vuelo Agregado");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        

    }//GEN-LAST:event_btnEnviarActionPerformed

    public void agregarDiasPrograma(int idPrograma){
        //Agregar en bd diaprograma
        
        DiaPrograma dp = new DiaPrograma();
        String idDia;
        
        if (cbxDia1.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia1.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia2.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia2.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia3.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia3.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia4.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia4.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia5.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia5.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia6.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia6.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
        if (cbxDia7.isSelected()){
            idDia = metodosCargarVista.obtenerIdDia(cbxDia7.getText());
            dp.setIdDia(idDia);
            dp.setIdPrograma(idPrograma);
            this.registrarDiaPrograma(dp);
            
        }
    }
    
    public void registrarDiaPrograma(DiaPrograma dp){
        try {
            DAODiaPrograma daoDiaP = new DiaProgramaImp();
            daoDiaP.registrar(dp);
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    private void cbxDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDia2ActionPerformed

    private void cbxDia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDia4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDia4ActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        DAOProgramaVuelo daoPV = new ProgramaVueloImp();
        Plantilla newReport;
        
        try {
            newReport = new Plantilla(daoPV.listarProgramasDia(metodosCargarVista.diaActual()), metodosCargarVista.fechaActual());
            newReport.crearPlantilla();
            JOptionPane.showMessageDialog(null, "Reporte Creado!, revise en la carpeta fuente");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProgramaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProgramaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProgramaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProgramaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProgramaVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnReporte;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbAeroDestino;
    private javax.swing.JComboBox<String> cbAeroOrigen;
    private javax.swing.JComboBox<String> cbAeroPlan;
    private javax.swing.JCheckBox cbxDia1;
    private javax.swing.JCheckBox cbxDia2;
    private javax.swing.JCheckBox cbxDia3;
    private javax.swing.JCheckBox cbxDia4;
    private javax.swing.JCheckBox cbxDia5;
    private javax.swing.JCheckBox cbxDia6;
    private javax.swing.JCheckBox cbxDia7;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> lineaAComboBox;
    // End of variables declaration//GEN-END:variables
}
